jobs:
  test:
    if: '!contains(github.event.head_commit.message, ''maven-release-plugin'')'
    name: test (JDK ${{ matrix.java_version }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.java_version }}
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-jdk-${{ matrix.java_version }}-maven-${{ hashFiles('**/pom.xml')
          }}
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-jdk-${{ matrix.java_version }}-maven-
    - continue-on-error: true
      name: Test
      run: build-bin/configure_test && build-bin/test ${{ matrix.maven_args }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - java_version: 11
          maven_args: -Prelease -Dgpg.skip -Dmaven.javadoc.skip=true
        - java_version: 21
  test-javadoc:
    if: '!contains(github.event.head_commit.message, ''maven-release-plugin'')'
    name: Test JavaDoc Builds
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '11'
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-jdk-11-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-jdk-11-maven-
    - continue-on-error: true
      name: Build JavaDoc
      run: ./mvnw clean javadoc:aggregate -Prelease
name: test
on:
  repository_dispatch:
    types: trigger-ga___test.yml
